# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-23 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Post'},
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.CharField(auto_created='2018-06-24 03:17:21', max_length=50, verbose_name='Created date'),
        ),
    ]
