# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-23 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180623_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Timestamp'),
        ),
    ]
